# Generated by Django 6.0.1 on 2026-02-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directorio', '0014_alter_contacto_mostrar_en_cumpleanios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cumpleanero',
            fields=[
            ],
            options={
                'verbose_name': 'Cumpleañero',
                'verbose_name_plural': 'Cumpleañeros',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('directorio.contacto',),
        ),
    ]
