# Generated by Django 5.2.11 on 2026-09-10 16:00

import apps.resguardos.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(default='Mi Empresa S.A. de C.V.', max_length=100)),
                ('nombre', models.CharField(help_text='Ej. Laptop Dell Latitude 5420', max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('identificador_interno', models.CharField(help_text='Tag de activo fijo o ID interno', max_length=50, unique=True)),
                ('estado_actual', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('DANIADO', 'Dañado / En Reparación'), ('BAJA', 'Dado de Baja')], default='USADO', max_length=20)),
                ('ubicacion_fisica_actual', models.CharField(blank=True, help_text='Ubicación física actual (ej. Almacén TI, Oficina 3B, En poder del empleado)', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Resguardo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now)),
                ('recibe_nombre', models.CharField(max_length=150, verbose_name='Nombre de quien recibe')),
                ('recibe_puesto_area', models.CharField(max_length=150, verbose_name='Puesto y área')),
                ('estado_equipo_entrega', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado')], default='USADO', max_length=10)),
                ('incluye_mouse', models.BooleanField(default=False)),
                ('incluye_cargador', models.BooleanField(default=False)),
                ('incluye_bateria', models.BooleanField(default=False)),
                ('otros_accesorios', models.CharField(blank=True, help_text='Especificar otros accesorios', max_length=255)),
                ('observaciones_entrega', models.TextField(blank=True)),
                ('firmado_digital', models.BooleanField(default=False, help_text='Indica si el resguardo ya fue firmado y devuelto escaneado')),
                ('archivo_resguardo_firmado', models.FileField(blank=True, help_text='Documento PDF o imagen del formato firmado', null=True, upload_to='resguardos_firmados/%Y/%m/')),
                ('estado_resguardo', models.CharField(choices=[('ACTIVO', 'Activo (En uso)'), ('DEVUELTO', 'Devuelto'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=15)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('estado_equipo_devolucion', models.CharField(blank=True, max_length=255, verbose_name='Estado del equipo al devolver')),
                ('observaciones_devolucion', models.TextField(blank=True)),
                ('elaboro_nombre', models.CharField(default='Generalista RH', max_length=100)),
                ('reviso_nombre', models.CharField(default='Especialista en DO', max_length=100)),
                ('aprobo_nombre', models.CharField(default='Contralor', max_length=100)),
                ('custodio_fisico_actual', models.CharField(blank=True, help_text='Persona o área que lo tiene resguardado físicamente en almacén/TI', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resguardos_created_by', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resguardos', to='resguardos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaResguardo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=apps.resguardos.models.evidencia_upload_path)),
                ('descripcion', models.CharField(blank=True, help_text='Ej. Rayón en la carcasa, Pantalla intacta', max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('resguardo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='resguardos.resguardo')),
            ],
        ),
    ]
