# Generated by Django 5.2.11 on 2026-08-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('acceder_explorador_direccion_obras', 'Acceder al explorador carpeta Dirección Obras')],
                'managed': False,
            },
        ),
    ]
