# Generated by Django 5.2.11 on 2026-08-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencias_moldes', '0002_alter_permiso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'default_permissions': (), 'managed': False, 'permissions': [('acceder_explorador_direccion_obras', 'Acceder al explorador carpeta Dirección Obras'), ('ver_foto', 'Ver foto en módulo de evidencias moldes')]},
        ),
    ]
