# Generated by Django 5.2.11 on 2026-06-29 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('identificador', models.CharField(blank=True, max_length=255, null=True)),
                ('serie', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('operador', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('clave', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=13)),
                ('domicilio', models.TextField()),
                ('ciudad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('regimen', models.CharField(choices=[('REGIMEN GENERAL DE LEY PERSONAS MORALES', 'REGIMEN GENERAL DE LEY PERSONAS MORALES'), ('PERSONAS FISICAS CON ACTIVIDAD EMPRESARIAL Y PROF', 'PERSONAS FISICAS CON ACTIVIDAD EMPRESARIAL Y PROF'), ('PERSONAS FISICAS CON ACTIVIDAD EMPRESARIAL Y PROF', 'PERSONAS FISICAS CON ACTIVIDAD EMPRESARIAL Y PROF')], max_length=255)),
                ('telefono', models.TextField(blank=True, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_servicio', models.CharField(max_length=255)),
                ('condiciones_pago', models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO'), ('CREDITO 15 DÍAS', 'CREDITO 15 DÍAS'), ('CREDITO 30 DÍAS', 'CREDITO 30 DÍAS')], max_length=255)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refacciones_servicios.equipo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refacciones_servicios.ordencompra')),
            ],
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='refacciones_servicios.proveedor'),
        ),
    ]
