# Generated by Django 5.2.11 on 2026-06-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones_servicios', '0002_alter_ordencompra_options_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cancelado', 'Cancelado')], default='borrador', max_length=255),
        ),
    ]
