# Generated by Django 5.2.11 on 2026-06-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones_servicios', '0003_ordencompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='concepto',
            field=models.CharField(choices=[('servicio', 'Servicio'), ('refacciones', 'Refacciones')], default='servicio', max_length=255),
        ),
    ]
