# Generated by Django 5.2.11 on 2026-06-30 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones_servicios', '0004_detalleordencompra_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fraccionamiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='obra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='refacciones_servicios.ordencompra'),
        ),
    ]
