# Generated by Django 5.2.11 on 2026-07-01 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones_servicios', '0005_ordencompra_fraccionamiento_ordencompra_obra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleordencompra',
            name='concepto',
        ),
    ]
