# Generated by Django 5.2.11 on 2026-07-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones_servicios', '0007_ordencompra_creado_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencompra',
            old_name='creado_por',
            new_name='creada_por',
        ),
    ]
