# Generated by Django 5.2.11 on 2026-07-02 00:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refacciones_servicios', '0008_rename_creado_por_ordencompra_creada_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='impuesto_cedular',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='impuesto_isr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
