# Generated by Django 6.0.1 on 2026-01-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('empresa', 'nombre'), 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
    ]
