# Generated by Django 6.0.1 on 2026-01-14 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_alter_area_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='aprobador_papeleria',
            field=models.CharField(blank=True, help_text='Encargado de aprobar la papelería del área', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='jefe_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='jefe_area'),
        ),
    ]
