# Generated by Django 6.0.1 on 2026-01-14 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0003_area_aprobador_papeleria_area_jefe_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='aprobador_papeleria',
            field=models.ForeignKey(blank=True, help_text='Encargado de aprobar la papelería del área', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprobador_papeleria_areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='area',
            name='jefe_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='areas'),
        ),
    ]
