# Generated by Django 6.0.1 on 2026-01-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_razonsocial_options'),
        ('rrhh', '0006_puesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=100, unique=True)),
                ('folio_consecutivo', models.PositiveIntegerField()),
                ('apoderado_legal', models.CharField(max_length=100)),
                ('nombre_trabajador', models.CharField(max_length=100)),
                ('edad_trabajador', models.IntegerField()),
                ('nacionalidad_trabajador', models.CharField(max_length=100)),
                ('sexo_trabajador', models.CharField(max_length=100)),
                ('rfc_trabajador', models.CharField(max_length=100)),
                ('domicilio_trabajador', models.TextField()),
                ('puesto_trabajador', models.CharField(max_length=100)),
                ('domicilio_trabajo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_firma', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='FolioContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'year')},
            },
        ),
    ]
