# Generated by Django 6.0.1 on 2026-01-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_contrato_foliocontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='domicilio_trabajo',
            field=models.TextField(max_length=100),
        ),
    ]
