# Generated by Django 6.0.1 on 2026-02-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_alter_contrato_domicilio_trabajo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foliocontrato',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='foliocontrato',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='FolioContrato',
        ),
    ]
