# Generated by Django 6.0.1 on 2026-02-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_alter_foliocontrato_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('empresa', 'nombre'), 'permissions': [('acceder_rrhh', 'Acceder al módulo de RRHH')], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
    ]
