# Generated by Django 6.0.1 on 2026-02-11 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puesto',
            options={'ordering': ('empresa', 'nombre')},
        ),
    ]
