# Generated by Django 5.2.11 on 2026-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_empresa_razones_sociales'),
        ('rrhh', '0013_alter_area_id_alter_puesto_id_alter_sede_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='empresa',
        ),
        migrations.AddField(
            model_name='sede',
            name='empresas',
            field=models.ManyToManyField(blank=True, help_text='Empresas que operan o son administradas desde esta sede.', related_name='sedes', to='core.empresa'),
        ),
    ]
