# Generated by Django 5.2.11 on 2026-08-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialADUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_username', models.CharField(max_length=150, verbose_name='Usuario AD')),
                ('ad_domain', models.CharField(default='TU_DOMINIO', max_length=150, verbose_name='Dominio AD')),
                ('_ad_password_encrypted', models.BinaryField(max_length='max', verbose_name='Contraseña Cifrada')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credencial_ad', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
        ),
    ]
