# Generated by Django 6.0.1 on 2026-01-12 19:54

import apps.directorio.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=apps.directorio.models.rename_contacto_image)),
                ('numero_empleado', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('extension', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('email_slack', models.EmailField(blank=True, help_text='Correo Electrónico registrado en Slack.', max_length=254, null=True)),
                ('slack_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mostrar_en_directorio', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(help_text='Empresa en la que está dado de alta administrativamente (nómina).', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.empresa')),
                ('jefe_directo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_cargo_de', to='directorio.contacto')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['empresa__nombre_corto', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido'],
            },
        ),
        migrations.CreateModel(
            name='EmailContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='directorio.contacto')),
            ],
            options={
                'unique_together': {('contacto', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TelefonoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=11)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='directorio.contacto')),
            ],
            options={
                'unique_together': {('contacto', 'telefono')},
            },
        ),
    ]
