# Generated by Django 6.0.1 on 2026-01-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcontacto',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailcontacto',
            name='esta_activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telefonocontacto',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telefonocontacto',
            name='esta_activo',
            field=models.BooleanField(default=False),
        ),
    ]
