# Generated by Django 6.0.1 on 2026-01-14 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_emailcontacto_es_principal_emailcontacto_esta_activo_and_more'),
        ('rrhh', '0002_alter_area_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.area', verbose_name='Área'),
        ),
    ]
