# Generated by Django 6.0.1 on 2026-01-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_razonsocial_options'),
        ('directorio', '0003_contacto_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa en la que está dado de alta administrativamente (nómina).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.empresa'),
        ),
    ]
