# Generated by Django 6.0.1 on 2026-01-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_alter_contacto_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['empresa__nombre_corto', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido'], 'permissions': [('acceder_directorio', 'Acceder al Directorio')]},
        ),
    ]
