# Generated by Django 6.0.1 on 2026-02-09 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_alter_contacto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='sede_administrativa',
            field=models.ForeignKey(blank=True, help_text='Sede responsable del alta y gestión del contacto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_administrados', to='directorio.sede'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='sedes_visibles',
            field=models.ManyToManyField(blank=True, help_text='Sedes donde este contacto aparece en el directorio', related_name='contactos_visibles', to='directorio.sede'),
        ),
    ]
