# Generated by Django 6.0.1 on 2026-02-09 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_sede_contacto_sede_administrativa_and_more'),
        ('rrhh', '0009_alter_foliocontrato_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.puesto', verbose_name='Puesto'),
        ),
    ]
