# Generated by Django 6.0.1 on 2026-02-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_contacto_puesto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='mostrar_en_directorio',
        ),
    ]
