# Generated by Django 6.0.1 on 2026-02-09 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_empresaiprange_empresa'),
        ('directorio', '0008_remove_contacto_mostrar_en_directorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='empresas_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='contactos_empresas_relacionadas', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa en la que está dado de alta administrativamente (nómina).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='core.empresa'),
        ),
    ]
