# Generated by Django 6.0.1 on 2026-02-10 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_empresaiprange_empresa'),
        ('directorio', '0009_contacto_empresas_relacionadas_and_more'),
        ('rrhh', '0010_alter_area_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telefonocontacto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='extension',
        ),
        migrations.AddField(
            model_name='telefonocontacto',
            name='es_celular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telefonocontacto',
            name='extension',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='rrhh.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='empresas_relacionadas',
            field=models.ManyToManyField(blank=True, help_text='Empresas adicionales con las que este contacto tiene relación.', related_name='contactos_empresas_relacionadas', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número De Empleado'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='rrhh.puesto', verbose_name='Puesto'),
        ),
        migrations.AlterUniqueTogether(
            name='telefonocontacto',
            unique_together={('contacto', 'telefono', 'extension')},
        ),
    ]
