# Generated by Django 6.0.1 on 2026-02-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0010_alter_telefonocontacto_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonocontacto',
            name='extension',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
