# Generated by Django 6.0.1 on 2026-02-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0011_alter_telefonocontacto_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeIPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_networks', to='directorio.sede')),
            ],
        ),
    ]
