# Generated by Django 6.0.1 on 2026-02-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0012_sedeiprange'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='mostrar_en_cumpleanios',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='mostrar_en_directorio',
            field=models.BooleanField(default=True),
        ),
    ]
