# Generated by Django 6.0.1 on 2026-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0013_contacto_mostrar_en_cumpleanios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='mostrar_en_cumpleanios',
            field=models.BooleanField(default=True, verbose_name='Mostrar en Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mostrar_en_directorio',
            field=models.BooleanField(default=True, verbose_name='Mostrar en Directorio'),
        ),
    ]
