# Generated by Django 6.0.1 on 2026-02-16 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0014_alter_contacto_mostrar_en_cumpleanios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sedeiprange',
            name='sede',
        ),
    ]
