# Generated by Django 6.0.1 on 2026-02-16 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0015_remove_sedeiprange_sede'),
        ('rrhh', '0012_sede_sedeiprange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='sede_administrativa',
            field=models.ForeignKey(blank=True, help_text='Sede responsable del alta y gestión del contacto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contactos_administrados', to='rrhh.sede'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='sedes_visibles',
            field=models.ManyToManyField(blank=True, help_text='Sedes donde este contacto aparece en el directorio', related_name='contactos_visibles', to='rrhh.sede'),
        ),
        migrations.DeleteModel(
            name='SedeIPRange',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
