# Generated by Django 6.0.1 on 2026-02-16 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_fecha_actualizacion_empresasoportesistemas_updated_at'),
        ('directorio', '0017_alter_contacto_area_alter_contacto_empresa_and_more'),
        ('rrhh', '0012_sede_sedeiprange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='rrhh.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa en la que está dado de alta administrativamente (nómina).', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='rrhh.puesto', verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='sede_administrativa',
            field=models.ForeignKey(help_text='Sede responsable del alta y gestión del contacto', on_delete=django.db.models.deletion.PROTECT, related_name='contactos_administrados', to='rrhh.sede'),
        ),
    ]
