# Generated by Django 6.0.1 on 2026-02-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0018_alter_contacto_area_alter_contacto_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='esta_archivado',
            field=models.BooleanField(default=False),
        ),
    ]
