# Generated by Django 6.0.1 on 2026-02-17 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0019_contacto_esta_archivado'),
        ('rrhh', '0012_sede_sedeiprange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='email_slack',
        ),
        migrations.AddField(
            model_name='emailcontacto',
            name='es_slack',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_cargo_de', to='directorio.contacto', verbose_name='Jefe'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Número de Empleado'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='primer_apellido',
            field=models.CharField(max_length=50, verbose_name='Primer Apellido'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='primer_nombre',
            field=models.CharField(max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='sede_administrativa',
            field=models.ForeignKey(help_text='Sede responsable del alta y gestión del contacto', on_delete=django.db.models.deletion.PROTECT, related_name='contactos_administrados', to='rrhh.sede', verbose_name='Sede Administrativa'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Apellido'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
