# Generated by Django 6.0.1 on 2026-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0020_remove_contacto_email_slack_emailcontacto_es_slack_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefonocontacto',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
