# Generated by Django 6.0.1 on 2026-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0021_alter_telefonocontacto_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='es_jefe',
            field=models.BooleanField(default=False),
        ),
    ]
