# Generated by Django 6.0.1 on 2026-02-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0022_contacto_es_jefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='es_jefe',
            field=models.BooleanField(default=False, verbose_name='Es jefe'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='esta_archivado',
            field=models.BooleanField(default=False, verbose_name='Contacto archivado'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_cargo_de', to='directorio.contacto', verbose_name='Jefe Directo'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='slack_id',
            field=models.CharField(blank=True, help_text='ID interno del usuario en Slack (no es el correo).', max_length=255, null=True, verbose_name='Slack ID'),
        ),
    ]
