# Generated by Django 5.2.11 on 2026-04-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0024_alter_contacto_id_alter_emailcontacto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='abreviatura_titulo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
