# Generated by Django 5.2.11 on 2026-04-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_razonsocial_logo'),
        ('directorio', '0025_contacto_abreviatura_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='razon_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='core.razonsocial'),
        ),
    ]
