# Generated by Django 5.2.11 on 2026-08-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0026_contacto_razon_social'),
        ('rrhh', '0013_alter_area_id_alter_puesto_id_alter_sede_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos', to='rrhh.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='rrhh.puesto', verbose_name='Puesto'),
        ),
    ]
