# Generated by Django 6.0.1 on 2026-01-12 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('clave', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/imagenes/')),
                ('codigo_vs_dp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Código VS DP')),
                ('numero_papeleria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número Papelería')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('impuesto', models.DecimalField(decimal_places=4, default=0.16, max_digits=20)),
                ('es_cuadro_basico', models.BooleanField(verbose_name='¿Pertenece al cuadro básico?')),
                ('mostrar_en_sitio', models.BooleanField(default=True, help_text='Seleccionar para que este artículo se pueda ver y seleccionar en el módulo de papelería')),
                ('empresas', models.ManyToManyField(blank=True, help_text='Que empresas pueden ver este artículo', related_name='articulos', to='core.empresa')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='papeleria.unidad')),
            ],
            options={
                'ordering': ['nombre'],
                'permissions': [('acceder_papeleria', 'Acceder papelería')],
            },
        ),
    ]
