# Generated by Django 6.0.1 on 2026-01-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='papeleria/articulos/imagenes/'),
        ),
    ]
