# Generated by Django 6.0.1 on 2026-01-12 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa'),
        ('papeleria', '0002_alter_articulo_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=100, unique=True)),
                ('folio_consecutivo', models.PositiveIntegerField(editable=False)),
                ('estado', models.CharField(choices=[('borrador', 'BORRADOR'), ('confirmada', 'CONFIRMADA'), ('enviada_aprobador', 'ENVÍADA AL APROBADOR'), ('autorizada_aprobador', 'AUTORIZADA POR APROBADOR'), ('enviada_compras', 'ENVIADA A COMPRAS'), ('autorizada_compras', 'AUTORIZADA POR COMPRAS'), ('enviada_contraloria', 'ENVIADA A CONTRALORÍA'), ('autorizada_contraloria', 'AUTORIZADA POR CONTRALORÍA'), ('esperando_entrega_articulo', 'ESPERANDO ENTREGA DE ARTÍCULO'), ('completada', 'COMPLETADA'), ('cancelada', 'CANCELADA')], default='borrador', max_length=255)),
                ('aprobo_solicitante', models.BooleanField(default=False)),
                ('aprobo_aprobador', models.BooleanField(default=False)),
                ('aprobo_compras', models.BooleanField(default=False)),
                ('aprobo_contraloria', models.BooleanField(default=False)),
                ('articulo_entregado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_papaleria_aprobador', to=settings.AUTH_USER_MODEL)),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_papeleria_compras', to=settings.AUTH_USER_MODEL)),
                ('contraloria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_papeleria_contraloria', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_papeleria', to='core.empresa')),
                ('requisicion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_relacionadas', to='papeleria.requisicion')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones_papeleria_solicitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisición',
                'verbose_name_plural': 'Requisiciones',
                'ordering': ['empresa', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetalleRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cantidad_liberada', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True, null=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_requisicion', to='papeleria.articulo')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_requisicion', to='papeleria.requisicion')),
            ],
            options={
                'unique_together': {('requisicion', 'articulo')},
            },
        ),
    ]
