# Generated by Django 6.0.1 on 2026-01-14 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_modulo_namespace'),
        ('papeleria', '0003_requisicion_detallerequisicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresaPapeleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_configuracion_papeleria', to=settings.AUTH_USER_MODEL)),
                ('contraloria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraloria_configuracion_papeleria', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_papeleria', to='core.empresa')),
            ],
        ),
    ]
