# Generated by Django 6.0.1 on 2026-01-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0004_configuracionempresapapeleria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicion',
            name='articulo_entregado',
        ),
    ]
