# Generated by Django 6.0.1 on 2026-01-14 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0005_remove_requisicion_articulo_entregado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='razon_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Razón de rechazo'),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='rechazador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_papeleria_rechazador', to=settings.AUTH_USER_MODEL),
        ),
    ]
