# Generated by Django 6.0.1 on 2026-01-14 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0006_requisicion_razon_rechazo_requisicion_rechazador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicion',
            options={'ordering': ['empresa', '-created_at'], 'permissions': [('aprobar_requisicion', 'Aprobar y rechazar Requisiciones')], 'verbose_name': 'Requisición', 'verbose_name_plural': 'Requisiciones'},
        ),
    ]
