# Generated by Django 6.0.1 on 2026-01-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0007_alter_requisicion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicion',
            options={'ordering': ['-created_at'], 'permissions': [('aprobar_requisicion', 'Aprobar y rechazar Requisiciones'), ('enviar_a_contraloria', 'Envíar requisiciones aprobadas por compras a contraloría')], 'verbose_name': 'Requisición', 'verbose_name_plural': 'Requisiciones'},
        ),
    ]
