# Generated by Django 6.0.1 on 2026-01-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0010_alter_requisicion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallerequisicion',
            old_name='cantidad_liberada',
            new_name='cantidad_autorizada',
        ),
    ]
