# Generated by Django 6.0.1 on 2026-01-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0011_rename_cantidad_liberada_detallerequisicion_cantidad_autorizada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicion',
            options={'ordering': ['-created_at'], 'permissions': [('aprobar_requisicion', 'Aprobar Requisiciones'), ('cancelar_requisicion', 'Cancelar o Rechazar Requisiciones'), ('enviar_requisicion_contraloria', 'Envíar requisiciones aprobadas por compras a contraloría'), ('autorizar_requisicion', 'Autorizar Requisiciones (Contraloría)')], 'verbose_name': 'Requisición', 'verbose_name_plural': 'Requisiciones'},
        ),
    ]
