# Generated by Django 6.0.1 on 2026-01-14 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0012_alter_requisicion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requisicion',
            name='fecha_autorizacion_contraloria',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
