# Generated by Django 6.0.1 on 2026-01-16 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0014_actividadrequisicion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='creada_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_papeleria_creada_por', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='aprobador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_papaleria_aprobador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='compras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_papeleria_compras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='contraloria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_papeleria_contraloria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_papeleria_solicitante', to=settings.AUTH_USER_MODEL),
        ),
    ]
