# Generated by Django 6.0.1 on 2026-01-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0015_requisicion_creada_por_alter_requisicion_aprobador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadrequisicion',
            options={'ordering': ['-created_at']},
        ),
    ]
