# Generated by Django 6.0.1 on 2026-01-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0016_alter_actividadrequisicion_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='es_papeleria_stock',
            field=models.BooleanField(default=False, help_text='Si se activa, la requisición se enviará directamente a Compras sin pasar por el aprobador del área.'),
        ),
    ]
