# Generated by Django 6.0.1 on 2026-01-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0018_requisicion_notas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Generales'),
        ),
    ]
