# Generated by Django 6.0.1 on 2026-01-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_razonsocial_options'),
        ('papeleria', '0019_alter_requisicion_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'year')},
            },
        ),
    ]
