# Generated by Django 6.0.1 on 2026-02-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0020_foliorequisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicion',
            name='folio',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='requisicion',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(),
        ),
    ]
