# Generated by Django 5.2.11 on 2026-09-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0022_alter_actividadrequisicion_id_alter_articulo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerequisicion',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='detallerequisicion',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
