# Generated by Django 5.2.11 on 2026-09-03 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0023_detallerequisicion_importe_detallerequisicion_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadrequisicion',
            name='tipo',
            field=models.CharField(choices=[('comment', 'Comentario'), ('system', 'Acción de Sistema')], default='comment', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividadrequisicion',
            name='contenido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividadrequisicion',
            name='requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='papeleria.requisicion'),
        ),
        migrations.AlterField(
            model_name='actividadrequisicion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_requisicion', to=settings.AUTH_USER_MODEL),
        ),
    ]
