# Generated by Django 5.2.11 on 2026-09-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0024_actividadrequisicion_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallerequisicion',
            old_name='importe',
            new_name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='detallerequisicion',
            name='precio',
        ),
    ]
