# Generated by Django 5.2.11 on 2026-10-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0025_rename_importe_detallerequisicion_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisicion',
            options={'ordering': ['-created_at'], 'permissions': [('acceder_papeleria', 'Acceder Al Módulo de Papelería'), ('aprobar_requisicion', 'Aprobar Requisiciones'), ('cancelar_requisicion', 'Cancelar o Rechazar Requisiciones'), ('enviar_requisicion_contraloria', 'Envíar requisiciones aprobadas por compras a contraloría'), ('autorizar_requisicion', 'Autorizar Requisiciones (Contraloría)')], 'verbose_name': 'Requisición', 'verbose_name_plural': 'Requisiciones'},
        ),
    ]
