# Generated by Django 6.0.1 on 2026-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('icono', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('permisos', models.CharField(help_text='papeleria.view_requisicion,fotos.view_foto', max_length=255, null=True)),
                ('url_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
