# Generated by Django 6.0.1 on 2026-01-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='permisos',
            field=models.CharField(blank=True, help_text='papeleria.view_requisicion,fotos.view_foto', max_length=255, null=True),
        ),
    ]
