# Generated by Django 6.0.1 on 2026-01-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_modulo_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(max_length=100, unique=True)),
                ('abreviatura', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
            ],
            options={
                'ordering': ['nombre_corto'],
            },
        ),
    ]
