# Generated by Django 6.0.1 on 2026-01-13 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_empresa', to='core.empresa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_empresa', to='core.modulo')),
            ],
            options={
                'unique_together': {('empresa', 'modulo')},
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='modulos',
            field=models.ManyToManyField(blank=True, related_name='empresas', through='core.ModuloEmpresa', to='core.modulo'),
        ),
    ]
