# Generated by Django 6.0.1 on 2026-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_moduloempresa_empresa_modulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='es_publico',
            field=models.BooleanField(default=False, help_text='El módulo puede ser accedido por cualquier empresa aunque no esté activo'),
        ),
    ]
