# Generated by Django 6.0.1 on 2026-01-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modulo_es_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='permite_anonimo',
            field=models.BooleanField(default=False, help_text='Puede ser accedido sin iniciar sesión'),
        ),
    ]
