# Generated by Django 6.0.1 on 2026-01-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_modulo_permite_anonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='theme',
            field=models.CharField(default='light', max_length=100),
        ),
    ]
