# Generated by Django 6.0.1 on 2026-01-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresa_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['nombre'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AddField(
            model_name='modulo',
            name='namespace',
            field=models.CharField(default='', help_text='Namespace de urls del módulo', max_length=100),
            preserve_default=False,
        ),
    ]
