# Generated by Django 6.0.1 on 2026-01-14 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_modulo_options_modulo_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='namespace',
        ),
    ]
