# Generated by Django 6.0.1 on 2026-01-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_modulo_namespace'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazonSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
