# Generated by Django 6.0.1 on 2026-01-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_razonsocial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='razonsocial',
            options={'verbose_name': 'Razón social', 'verbose_name_plural': 'Razones sociales'},
        ),
    ]
