# Generated by Django 6.0.1 on 2026-01-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_razonsocial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='razonsocial',
            options={'ordering': ['nombre'], 'verbose_name': 'Razón social', 'verbose_name_plural': 'Razones sociales'},
        ),
    ]
