# Generated by Django 6.0.1 on 2026-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_razonsocial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsocial',
            name='abreviatura',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razonsocial',
            name='nombre_corto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='razonsocial',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
