# Generated by Django 6.0.1 on 2026-02-09 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_razonsocial_abreviatura_razonsocial_nombre_corto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaIPRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_ranges', to='core.empresa')),
            ],
        ),
    ]
