# Generated by Django 6.0.1 on 2026-02-09 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_empresaiprange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaiprange',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_networks', to='core.empresa'),
        ),
    ]
