# Generated by Django 6.0.1 on 2026-02-13 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_empresaiprange_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSoporteSistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificar_por_correo', models.BooleanField(default=True)),
                ('notificar_por_slack', models.BooleanField(default=False)),
                ('correo_soporte', models.EmailField(blank=True, help_text='Correo donde se recibirán notificaciones de tickets', max_length=254, null=True)),
                ('slack_channel', models.CharField(blank=True, help_text='ID del canal de Slack', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_soporte', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Configuración Soporte Sistemas',
                'verbose_name_plural': 'Configuraciones Soporte Sistemas',
            },
        ),
    ]
