# Generated by Django 6.0.1 on 2026-02-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_empresasoportesistemas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresasoportesistemas',
            old_name='fecha_actualizacion',
            new_name='updated_at',
        ),
    ]
