# Generated by Django 6.0.1 on 2026-02-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_fecha_actualizacion_empresasoportesistemas_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('acceder_sistema_contratos', 'Acceder al Módulo de Sistema De Contratos'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
