# Generated by Django 6.0.1 on 2026-02-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_permiso'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='url_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
