# Generated by Django 5.2.11 on 2026-04-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_empresa_id_alter_empresaiprange_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsocial',
            name='prefijo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
