# Generated by Django 5.2.11 on 2026-04-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_razonsocial_prefijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsocial',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
