# Generated by Django 5.2.11 on 2026-07-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_razonsocial_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'default_permissions': (), 'managed': False, 'permissions': (('acceder_sistema_contratos', 'Acceder al Módulo de Sistema De Contratos'), ('generar_reporte_presupuestos_vs', 'Ver y Generar Excel del reporte de presupuestos del VS Control'))},
        ),
    ]
