# Generated by Django 5.2.11 on 2026-08-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_permiso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='requiere_ip',
            field=models.BooleanField(default=False, help_text='Restringe la visibilidad y acceso según la IP del usuario'),
        ),
        migrations.CreateModel(
            name='ModuloIPRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(help_text='Ej: 172.17.4.0/24 o 127.0.0.1/32', max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_networks', to='core.modulo')),
            ],
        ),
    ]
