# Generated by Django 5.2.11 on 2026-08-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_modulo_requiere_ip_moduloiprange'),
    ]

    operations = [
        migrations.AddField(
            model_name='razonsocial',
            name='domicilio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='razonsocial',
            name='rfc',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
