# Generated by Django 5.2.11 on 2026-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_razonsocial_domicilio_razonsocial_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razones_sociales',
            field=models.ManyToManyField(blank=True, help_text='Razones sociales vinculadas a esta unidad de negocio.', related_name='empresas', to='core.razonsocial'),
        ),
    ]
