# Generated by Django 6.0.1 on 2026-02-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contratista',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='rfc',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='telefono',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono'),
        ),
    ]
