# Generated by Django 6.0.1 on 2026-02-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0002_tipovivienda_alter_contratista_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoVivienda',
            new_name='Estructura',
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subpaquetes', to='destajos.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, unique=True)),
                ('nombre', models.TextField()),
                ('es_unitario', models.BooleanField(default=True, help_text='Si depende del número de viviendas')),
                ('unidad', models.CharField(blank=True, choices=[('vivienda', 'VIVIENDA')], default='VIVIENDA', help_text='m2, pza, vivienda, ml, etc', max_length=50)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trabajos', to='destajos.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='EstructuraTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='destajos.estructura')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destajos.trabajo')),
            ],
            options={
                'unique_together': {('estructura', 'trabajo')},
            },
        ),
    ]
