# Generated by Django 6.0.1 on 2026-02-05 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0003_rename_tipovivienda_estructura_paquete_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratista',
            options={'ordering': ['primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido']},
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='unidad',
            field=models.CharField(blank=True, choices=[('vivienda', 'VIVIENDA')], default='vivienda', help_text='m2, pza, vivienda, ml, etc', max_length=50),
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('etapa', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='destajos.estructura')),
            ],
        ),
        migrations.CreateModel(
            name='ContratistaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='destajos.contratista')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destajos.trabajo')),
            ],
            options={
                'unique_together': {('contratista', 'trabajo')},
            },
        ),
        migrations.CreateModel(
            name='PrecioContratista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('vivienda', 'VIVIENDA')], max_length=50)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destajos.contratista')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destajos.trabajo')),
            ],
            options={
                'indexes': [models.Index(fields=['contratista', 'trabajo', 'vigente_desde'], name='destajos_pr_contrat_125b2d_idx')],
            },
        ),
    ]
