# Generated by Django 6.0.1 on 2026-02-05 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0004_alter_contratista_options_alter_trabajo_unidad_obra_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='Cantidad de viviendas'),
        ),
        migrations.CreateModel(
            name='Destajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autoriza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destajos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destajos', to='destajos.contratista')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destajos', to='destajos.obra')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destajos_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DestajoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('entrega', models.DecimalField(decimal_places=2, help_text='Avance o número de entregas', max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(choices=[('vivienda', 'VIVIENDA')], default='vivienda', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('surtido', models.BooleanField(default=False)),
                ('destajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='destajos.destajo')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='destajos.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='destajos.estructura')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='destajos.obra')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('obra', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='EstadoTrabajoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('por_realizar', 'Por realizar'), ('realizado', 'Realizado'), ('pagado', 'Pagado'), ('no_aplica', 'No aplica')], default='pendiente', max_length=20)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='destajos.trabajo')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='destajos.vivienda')),
            ],
            options={
                'unique_together': {('vivienda', 'trabajo')},
            },
        ),
    ]
