# Generated by Django 6.0.1 on 2026-02-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0005_alter_obra_cantidad_destajo_destajodetalle_vivienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destajodetalle',
            name='descripcion',
        ),
    ]
