# Generated by Django 6.0.1 on 2026-02-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0006_remove_destajodetalle_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destajodetalle',
            name='entrega',
        ),
        migrations.AddField(
            model_name='destajodetalle',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destajodetalle',
            name='surtido',
            field=models.PositiveIntegerField(),
        ),
    ]
