# Generated by Django 6.0.1 on 2026-02-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0007_remove_destajodetalle_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destajodetalle',
            name='surtido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
