# Generated by Django 6.0.1 on 2026-02-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0008_alter_destajodetalle_surtido'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioDestajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='destajo',
            name='folio',
            field=models.CharField(default=None, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destajo',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='destajodetalle',
            unique_together={('destajo', 'trabajo')},
        ),
    ]
