# Generated by Django 6.0.1 on 2026-02-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0009_foliodestajo_destajo_folio_destajo_folio_consecutivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destajo',
            name='estado',
            field=models.CharField(choices=[('borrador', 'BORRADOR'), ('publicado', 'PUBLICADO'), ('cancelado', 'CANCELADO')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='destajo',
            name='folio',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='destajo',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(),
        ),
    ]
