# Generated by Django 6.0.1 on 2026-02-06 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0010_destajo_estado_alter_destajo_folio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratista',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='contratista',
            old_name='primer_apellido',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='primer_nombre',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='contratista',
            name='segundo_nombre',
        ),
        migrations.AlterField(
            model_name='preciocontratista',
            name='unidad',
            field=models.CharField(choices=[('vivienda', 'VIVIENDA')], default='vivienda', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='preciocontratista',
            unique_together={('contratista', 'trabajo', 'precio', 'vigente_desde', 'vigente_hasta')},
        ),
    ]
