# Generated by Django 6.0.1 on 2026-02-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0011_alter_contratista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratista',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
