# Generated by Django 6.0.1 on 2026-02-06 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0012_alter_contratista_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='preciocontratista',
            name='estructura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='destajos.estructura'),
        ),
    ]
