# Generated by Django 6.0.1 on 2026-02-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0013_preciocontratista_estructura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete',
            options={'ordering': ('padre__clave', 'padre_id', 'orden', 'clave')},
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='nombre',
            field=models.CharField(max_length=512),
        ),
    ]
