# Generated by Django 6.0.1 on 2026-02-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0014_alter_paquete_options_alter_trabajo_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ('paquete', 'nombre')},
        ),
        migrations.RemoveField(
            model_name='destajo',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='estructura',
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contratista',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contratista',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='preciocontratista',
            name='contratista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='destajos.contratista'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='clave',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('cantidad_viviendas', models.PositiveIntegerField()),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manzanas', to='destajos.estructura')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manzanas', to='destajos.obra')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='destajo',
            name='manzana',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='destajos', to='destajos.manzana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='manzana',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='destajos.manzana'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together={('manzana', 'numero')},
        ),
        migrations.RemoveField(
            model_name='vivienda',
            name='obra',
        ),
    ]
