# Generated by Django 6.0.1 on 2026-02-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_razonsocial_options'),
        ('destajos', '0015_alter_trabajo_options_remove_destajo_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAgrupador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='destajo',
            name='manzana',
        ),
        migrations.AddField(
            model_name='obra',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='razon_social',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='core.razonsocial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Agrupador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('cantidad_viviendas', models.PositiveIntegerField()),
                ('estructura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupadores', to='destajos.estructura')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agrupadores', to='destajos.obra')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agrupadores', to='destajos.tipoagrupador')),
            ],
            options={
                'ordering': ['tipo__nombre', 'numero'],
                'unique_together': {('obra', 'tipo', 'numero')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='destajo',
            name='agrupador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='destajos', to='destajos.agrupador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vivienda',
            name='agrupador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='destajos.agrupador'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together={('agrupador', 'numero')},
        ),
        migrations.RemoveField(
            model_name='vivienda',
            name='manzana',
        ),
        migrations.DeleteModel(
            name='Manzana',
        ),
    ]
