# Generated by Django 6.0.1 on 2026-02-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0016_tipoagrupador_remove_destajo_manzana_obra_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estructura',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estadotrabajovivienda',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_trabajo', to='destajos.vivienda'),
        ),
    ]
