# Generated by Django 6.0.1 on 2026-02-11 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0017_estructura_abreviatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destajo',
            name='agrupador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destajos', to='destajos.agrupador', verbose_name='Fraccionamiento'),
        ),
        migrations.AlterField(
            model_name='destajo',
            name='folio',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='destajo',
            name='folio_consecutivo',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='unidad',
            field=models.CharField(blank=True, choices=[('vivienda', 'VIVIENDA')], default='vivienda', max_length=50),
        ),
    ]
