# Generated by Django 6.0.1 on 2026-02-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0018_alter_destajo_agrupador_alter_destajo_folio_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preciocontratista',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='preciocontratista',
            name='estructura',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='destajos.estructura'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='preciocontratista',
            unique_together={('contratista', 'trabajo', 'estructura', 'precio', 'vigente_desde', 'vigente_hasta')},
        ),
    ]
