# Generated by Django 6.0.1 on 2026-02-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0019_alter_preciocontratista_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadotrabajovivienda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('por_realizar', 'Por realizar'), ('realizado', 'Realizado'), ('pagado', 'Pagado'), ('na', 'No aplica')], default='pendiente', max_length=20),
        ),
    ]
