# Generated by Django 6.0.1 on 2026-02-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0020_alter_estadotrabajovivienda_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete',
            options={'ordering': ('clave',)},
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='orden',
        ),
    ]
