# Generated by Django 5.2.11 on 2026-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0022_alter_trabajo_options_alter_agrupador_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [['acceder_destajos', 'Acceder al módulo de destajos']],
                'managed': False,
            },
        ),
    ]
