# Generated by Django 5.2.11 on 2026-07-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0023_permissions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agrupador',
            unique_together=set(),
        ),
    ]
