# Generated by Django 5.2.11 on 2026-07-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0024_alter_agrupador_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='direccion',
        ),
        migrations.AddField(
            model_name='obra',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
