# Generated by Django 5.2.11 on 2026-07-07 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0025_remove_obra_direccion_obra_ciudad_obra_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraAdicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_base', models.DecimalField(decimal_places=2, default=1, help_text='Cantidad de este trabajo adicional asignado por cada vivienda', max_digits=10)),
                ('agrupador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras_adicionales', to='destajos.agrupador')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras_adicionales', to='destajos.trabajo')),
            ],
            options={
                'verbose_name': 'Obra Adicional',
                'verbose_name_plural': 'Obras Adicionales',
                'unique_together': {('agrupador', 'trabajo')},
            },
        ),
    ]
