# Generated by Django 5.2.11 on 2026-07-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destajos', '0026_obraadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadotrabajovivienda',
            name='es_obra_adicional',
            field=models.BooleanField(default=False),
        ),
    ]
