# Generated by Django 5.2.11 on 2026-10-01 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas_precios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineareglaprecio',
            options={'permissions': (('ver_listas_precios', 'Ver Listas De Precios (DOMINUM, ABRAHAM)'),), 'verbose_name': 'Regla de Precio por Línea'},
        ),
    ]
