# Generated by Django 5.2.11 on 2026-08-17 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaNotificacionSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuarioSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('slack_id', models.CharField(max_length=100, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_slack', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DestinatarioSlack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('usuario_slack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_usuario_slack', to='slack.configuracionusuarioslack')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='slack.listanotificacionslack')),
            ],
            options={
                'unique_together': {('list', 'usuario_slack')},
            },
        ),
    ]
