# Generated by Django 5.2.11 on 2026-04-20 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0021_razonsocial_prefijo'),
        ('directorio', '0024_alter_contacto_id_alter_emailcontacto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.TextField()),
                ('rfc', models.CharField(max_length=13)),
                ('condicion_pago', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('uso_cfdi', models.CharField(choices=[('G01', 'G01'), ('G02', 'G02'), ('G03', 'G03'), ('I01', 'I01'), ('I02', 'I02'), ('I03', 'I03'), ('I04', 'I04'), ('I05', 'I05'), ('I06', 'I06'), ('I07', 'I07'), ('I08', 'I08'), ('D01', 'D01'), ('D02', 'D02'), ('D03', 'D03'), ('D04', 'D04'), ('D05', 'D05'), ('D06', 'D06'), ('D07', 'D07'), ('D08', 'D08'), ('D09', 'D09'), ('D10', 'D10'), ('P01', 'P01')], max_length=10)),
                ('metodo_pago', models.CharField(choices=[('PPD', 'PPD'), ('PUE', 'PUE')], max_length=3)),
                ('forma_pago', models.CharField(choices=[('01 Efectivo', '01 Efectivo'), ('02 Cheque', '02 Cheque'), ('03 Transferencia', '03 Transferencia'), ('04 Tarjet Crèdito', '04 Tarjet Crèdito'), ('05 Monedero Electrónico', '05 Monedero Electrónico'), ('06 Dinero Electrónico', '06 Dinero Electrónico'), ('08 Vales de Despensa', '08 Vales de Despensa'), ('12 Dación de Pago', '12 Dación de Pago'), ('13 Pago por subrogaciòn', '13 Pago por subrogaciòn'), ('14 Pago por consignación', '14 Pago por consignación'), ('17 Compensación', '17 Compensación'), ('23 Novación', '23 Novación'), ('24 Confusión', '24 Confusión'), ('25 Remisiòn de deuda', '25 Remisiòn de deuda'), ('26 Prescripciòn o Caducidad', '26 Prescripciòn o Caducidad'), ('27 A satisfacción del Acreedor', '27 A satisfacción del Acreedor'), ('28 Tarjeta de Débito', '28 Tarjeta de Débito'), ('29 Tarjeta de Servicios', '29 Tarjeta de Servicios'), ('30 Aplicación de anticipos', '30 Aplicación de anticipos'), ('31 Intermediario Pagos', '31 Intermediario Pagos'), ('99 Por definir', '99 Por definir')], max_length=100)),
                ('utilizado_en', models.TextField()),
                ('fecha_orden', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('fecha_entrega', models.DateField()),
                ('lugar_entrega', models.TextField()),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retencion_cedular', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('autoriza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_autorizador', to='directorio.contacto')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_creada_por', to='directorio.contacto')),
                ('razon_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.razonsocial')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_solicitante', to='directorio.contacto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='compras.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='compras.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenFolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=10)),
                ('folio_actual', models.PositiveIntegerField(default=0)),
                ('razon_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folios_orden', to='core.razonsocial')),
            ],
        ),
    ]
