# Generated by Django 5.2.11 on 2026-04-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
