# Generated by Django 5.2.11 on 2026-04-20 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detalleorden_orden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='creada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_creada_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
