# Generated by Django 5.2.11 on 2026-04-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_orden_creada_por'),
        ('directorio', '0025_contacto_abreviatura_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='autoriza',
            field=models.ForeignKey(limit_choices_to={'usuario__groups__name': 'AUTORIZADORES'}, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_autorizador', to='directorio.contacto'),
        ),
    ]
