# Generated by Django 5.2.11 on 2026-06-29 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_orden_autoriza'),
        ('core', '0022_razonsocial_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha_orden',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de la orden'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='forma_pago',
            field=models.CharField(choices=[('01 Efectivo', '01 Efectivo'), ('02 Cheque', '02 Cheque'), ('03 Transferencia', '03 Transferencia'), ('04 Tarjet Crèdito', '04 Tarjet Crèdito'), ('05 Monedero Electrónico', '05 Monedero Electrónico'), ('06 Dinero Electrónico', '06 Dinero Electrónico'), ('08 Vales de Despensa', '08 Vales de Despensa'), ('12 Dación de Pago', '12 Dación de Pago'), ('13 Pago por subrogaciòn', '13 Pago por subrogaciòn'), ('14 Pago por consignación', '14 Pago por consignación'), ('17 Compensación', '17 Compensación'), ('23 Novación', '23 Novación'), ('24 Confusión', '24 Confusión'), ('25 Remisiòn de deuda', '25 Remisiòn de deuda'), ('26 Prescripciòn o Caducidad', '26 Prescripciòn o Caducidad'), ('27 A satisfacción del Acreedor', '27 A satisfacción del Acreedor'), ('28 Tarjeta de Débito', '28 Tarjeta de Débito'), ('29 Tarjeta de Servicios', '29 Tarjeta de Servicios'), ('30 Aplicación de anticipos', '30 Aplicación de anticipos'), ('31 Intermediario Pagos', '31 Intermediario Pagos'), ('99 Por definir', '99 Por definir')], max_length=100, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='lugar_entrega',
            field=models.TextField(verbose_name='Lugar de entrega'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(choices=[('PPD', 'PPD'), ('PUE', 'PUE')], max_length=3, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='razon_social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='core.razonsocial', verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='retencion_cedular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención Cedular'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención ISR'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='uso_cfdi',
            field=models.CharField(choices=[('G01', 'G01'), ('G02', 'G02'), ('G03', 'G03'), ('I01', 'I01'), ('I02', 'I02'), ('I03', 'I03'), ('I04', 'I04'), ('I05', 'I05'), ('I06', 'I06'), ('I07', 'I07'), ('I08', 'I08'), ('D01', 'D01'), ('D02', 'D02'), ('D03', 'D03'), ('D04', 'D04'), ('D05', 'D05'), ('D06', 'D06'), ('D07', 'D07'), ('D08', 'D08'), ('D09', 'D09'), ('D10', 'D10'), ('P01', 'P01')], max_length=10, verbose_name='Uso de CFDI'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='utilizado_en',
            field=models.TextField(verbose_name='Para ser utilizado en'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='condicion_pago',
            field=models.CharField(max_length=100, verbose_name='Condición de pago'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=13, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
