# Generated by Django 5.2.11 on 2026-07-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_orden_fecha_entrega_alter_orden_fecha_orden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
