# Generated by Django 5.2.11 on 2026-07-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_detalleorden_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleorden',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=24),
        ),
    ]
