# Generated by Django 5.2.11 on 2026-08-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_detalleorden_precio_unitario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='orden',
            name='retencion_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retención 3'),
        ),
    ]
