# Generated by Django 5.2.11 on 2026-08-26 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_orden_options_orden_retencion_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='retencion_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retención 3 (%)'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='retencion_cedular',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retención Cedular (%)'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje del 0 al 100', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retención ISR (%)'),
        ),
    ]
