# Generated by Django 5.2.11 on 2026-08-28 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_orden_retencion_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='retencion_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Retención Fletes (%)'),
        ),
    ]
