# Generated by Django 5.2.11 on 2026-10-07 16:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('ganador_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('canjeado', models.BooleanField(default=False)),
                ('fecha_canje', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='regalos')),
            ],
        ),
    ]
