# Generated by Django 5.2.11 on 2026-10-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regalos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regalo',
            name='fecha_canje',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='regalo',
            name='ganador_nombre',
            field=models.CharField(blank=True, editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='regalo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='regalos'),
        ),
    ]
