# Generated by Django 5.2.11 on 2026-07-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('descripcion', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descripcion')),
                ('direccion', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Direccion')),
                ('created', models.DateTimeField(db_column='Created', db_comment='Fecha en la se creo el registr')),
                ('imagen', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Imagen')),
                ('idcliente', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IdCliente', db_comment='ID del cliente al que pertenec', max_length=13)),
                ('idfraccionamiento', models.DecimalField(db_column='IdFraccionamiento', decimal_places=0, max_digits=5)),
                ('nombrecorto', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NombreCorto', max_length=100)),
                ('idobra', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='IdObra', max_length=20, primary_key=True, serialize=False)),
                ('codigopostal', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CodigoPostal', max_length=10)),
                ('calle', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Calle', max_length=60)),
                ('numeroexterior', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NumeroExterior', max_length=30)),
                ('numerointerior', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='NumeroInterior', max_length=30)),
                ('colonia', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Colonia', max_length=60)),
                ('localidad', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Localidad', max_length=60)),
                ('identidadfederativa', models.DecimalField(db_column='IdEntidadFederativa', decimal_places=0, max_digits=5)),
                ('municipio', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Municipio', max_length=60)),
                ('pais', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pais', max_length=30)),
                ('domicilio', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Domicilio')),
            ],
            options={
                'db_table': 'Obras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presupuestoxpartidas',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('claveconceptoobra', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ClaveConceptoObra', db_comment='Clave de usuario para el conce', max_length=20)),
                ('descripcion', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Descripcion', db_comment='Descripci¾n del concepto')),
                ('nivelidentacion', models.DecimalField(db_column='NivelIdentacion', db_comment='Nivel de identaci¾n del nodo, ', decimal_places=0, max_digits=2)),
                ('idconceptoobra', models.DecimalField(db_column='IdConceptoObra', db_comment='Id interno del concepto de obr', decimal_places=0, max_digits=10)),
                ('idconceptopadre', models.DecimalField(db_column='IdConceptoPadre', db_comment='Id del concepto padre al que s', decimal_places=0, max_digits=10)),
                ('signo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Signo', db_comment='Signo que identifica + Cuando ', max_length=1)),
                ('visible', models.IntegerField(db_column='Visible', db_comment='Campo auxiliar para el datatab')),
                ('unidad', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Unidad', db_comment='Unidad del concepto', max_length=20)),
                ('cantidad', models.FloatField(db_column='Cantidad', db_comment='Volumen del concepto, acumulad')),
                ('preciopresupuestado', models.FloatField(db_column='PrecioPresupuestado', db_comment='Precio del concepto')),
                ('esagrupador', models.IntegerField(db_column='EsAgrupador', db_comment='Indica si el concepto es un ag')),
                ('costodirecto', models.FloatField(db_column='CostoDirecto', db_comment='Costo directo total del concep')),
                ('idusuariocreo', models.DecimalField(db_column='IdUsuarioCreo', decimal_places=0, max_digits=5)),
                ('created', models.DateTimeField(db_column='Created')),
                ('idordencambio', models.DecimalField(db_column='IdOrdenCambio', decimal_places=0, max_digits=5)),
            ],
            options={
                'db_table': 'PresupuestoxPartidas',
                'managed': False,
            },
        ),
    ]
