# Generated by Django 5.2.11 on 2026-02-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('key', models.BigAutoField(db_column='KeyClassification', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Name', max_length=100)),
                ('descripcion', models.TextField(db_column='Description')),
            ],
            options={
                'db_table': 'dbo.catClassification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetClasificacion',
            fields=[
                ('key', models.BigAutoField(db_column='KeyDetClassification', primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_column='Code', max_length=100)),
                ('descripcion', models.TextField(db_column='Description')),
            ],
            options={
                'verbose_name': 'Clasificacion',
                'verbose_name_plural': 'Clasificaciones',
                'db_table': 'dbo.detClassification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('key', models.BigAutoField(db_column='KeyHoliday', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='HolDate')),
                ('descripcion', models.TextField(db_column='Description')),
                ('esta_publicado', models.BooleanField(db_column='IsPosted', default=False)),
                ('lock_user', models.PositiveIntegerField(db_column='LockUser', default=0)),
                ('lock_for_delete', models.PositiveIntegerField(db_column='LockForDelete', default=0)),
            ],
            options={
                'verbose_name': 'Día Festivo',
                'db_table': 'dbo.CatHolidays',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('key', models.BigAutoField(db_column='KeyEmployee', primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='Number', max_length=100)),
                ('status_val', models.PositiveIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], db_column='StatusVal')),
                ('badge', models.CharField(db_column='Badge', db_index=True, max_length=128, unique=True)),
                ('name1', models.CharField(db_column='Name1', max_length=100)),
                ('name2', models.CharField(db_column='Name2', max_length=100)),
                ('last_name1', models.CharField(db_column='LastName1', max_length=100)),
                ('last_name2', models.CharField(db_column='LastName2', max_length=100)),
                ('sex', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], db_column='Sex', max_length=100)),
                ('hire_date', models.DateField(db_column='HireDate')),
            ],
            options={
                'db_table': 'dbo.catEmployee',
                'ordering': ['name1', 'name2', 'last_name1', 'last_name2'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('key', models.BigAutoField(db_column='KeyPunch', primary_key=True, serialize=False)),
                ('transaction', models.PositiveIntegerField(db_column='KeyTrans')),
                ('belong_date', models.DateField(db_column='BelongDate')),
                ('punch_time', models.DateTimeField(db_column='PunchTime')),
            ],
            options={
                'db_table': 'dbo.detPunches',
                'ordering': ['belong_date', 'punch_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reloj',
            fields=[
                ('key', models.BigAutoField(db_column='KeyTerminal', primary_key=True, serialize=False)),
                ('terminal', models.PositiveIntegerField(db_column='terminal', unique=True)),
                ('descripcion', models.TextField(db_column='Descrip')),
                ('ip', models.GenericIPAddressField(db_column='ipdir')),
                ('puerto', models.PositiveIntegerField(db_column='ipidport')),
            ],
            options={
                'db_table': 'dbo.catCLOCKS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransaccionReloj',
            fields=[
                ('key', models.BigAutoField(db_column='KeyTransaction', primary_key=True, serialize=False)),
                ('date', models.CharField(db_column='PunchDate', max_length=255)),
                ('time_str', models.CharField(db_column='PTimeStr', max_length=255)),
            ],
            options={
                'db_table': 'dbo.detPunchesIni',
                'managed': False,
            },
        ),
    ]
