# Generated by Django 5.2.11 on 2026-03-25 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDiarioAsistencia',
            fields=[
                ('key', models.BigAutoField(db_column='KeyPunchDay', primary_key=True, serialize=False)),
                ('record_date', models.DateField(db_column='RecordDate')),
                ('first_in', models.DecimalField(db_column='FirstIN', decimal_places=3, max_digits=8)),
                ('last_ot', models.DecimalField(db_column='LastOT', decimal_places=3, max_digits=8)),
            ],
            options={
                'db_table': 'dbo.detPUNCHMaster',
                'ordering': ['-record_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('key', models.BigAutoField(db_column='KeyPolicy', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=20)),
                ('description', models.CharField(db_column='Description', max_length=50)),
            ],
            options={
                'db_table': 'dbo.catPolicy',
            },
        ),
        migrations.AlterModelOptions(
            name='registroasistencia',
            options={'managed': False, 'ordering': ['-belong_date', '-punch_time']},
        ),
        migrations.CreateModel(
            name='ExcepcionAsistencia',
            fields=[
                ('control_asistencia', models.ForeignKey(db_column='KeyPunchDay', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asistencias.controldiarioasistencia')),
                ('comentario', models.TextField(db_column='Comment')),
            ],
            options={
                'db_table': 'dbo.detPunchDayExcep',
                'managed': False,
            },
        ),
    ]
