# Generated by Django 5.2.11 on 2026-03-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_controldiarioasistencia_politica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politica',
            options={'managed': False},
        ),
    ]
