# Generated by Django 5.2.11 on 2026-09-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPrecioOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_art', models.CharField(db_index=True, max_length=20, unique=True)),
                ('precio_lista_custom', models.DecimalField(decimal_places=4, max_digits=12)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaReglaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_lin', models.CharField(max_length=10)),
                ('num_lista', models.IntegerField()),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('porcentaje_utilidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Regla de Precio por Línea',
                'unique_together': {('cve_lin', 'num_lista')},
            },
        ),
    ]
