# Generated by Django 5.2.11 on 2026-09-30 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sae', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineaReglaPrecio',
        ),
        migrations.DeleteModel(
            name='ProductoPrecioOverride',
        ),
    ]
