# Generated by Django 5.2.11 on 2026-09-04 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_sae_coi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoContabilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_sae', models.CharField(db_index=True, max_length=20)),
                ('uuid_xml', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('empresa_suffix', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO_COI', 'Enviado a COI'), ('ERROR', 'Error en integración')], default='PENDIENTE', max_length=20)),
                ('poliza_generada', models.CharField(blank=True, max_length=50, null=True)),
                ('ejercicio', models.IntegerField(blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('folio_sae', 'empresa_suffix')},
            },
        ),
    ]
