# Generated by Django 5.2.11 on 2026-09-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_sae_coi', '0002_documentocontabilizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_documentos', 'Ver Documentos Polizas'), ('add_poliza', 'Agregar Poliza en COI')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
