# Generated by Django 5.2.11 on 2026-09-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaz_sae_coi', '0003_permiso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocontabilizado',
            name='folio_sae',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
